### ISSUE TITLE
Update material-ui?

### ISSUE THREAD

**Issue by fastrocket** [dsuryd/dotNetify-react-template#30]
I wanted to use Tables from Material-UI (https://material-ui.com/demos/tables/), but the version installed with the Dotnetify React Demo VS2017 didn't seem to have it. So I did an "npm install @material-ui/core" which seemed to work (haven't integrated with the backend yet), but now there are two versions of material-ui in the package.json file. 

I'm relatively new to React, so I was curious what the proper way to add/update the latest Material-UI to Dotnetify was?

**Comment by dsuryd** [comment]
The template uses an old version, and it seems the package signature has changed.  You can uninstall that old one, but no guarantee things will stay working if the new version happens to have breaking changes.

**Comment by roozbehid-ic** [comment]
I tried to do the update but it was hard! I have a really ugly UI now!
I wish someone do a PR to make the update...I couldnt :(

**Comment by dsuryd** [comment]
I wish someone would do a PR too :)    I did look at it a while ago, and agree it's pretty hard since they did so many breaking changes.   I think the most sensible thing would be to start fresh from their latest template here: https://www.creative-tim.com/product/material-dashboard-react, and integrate it with dotNetify.  This should be a much easier path.

**Comment by dsuryd** [comment]
The template has been updated to latest Material UI and .NET Core 3.0.
