### ISSUE TITLE
Fix SSR in Micro-Frontend

### ISSUE THREAD

**Issue by Elijah23Johnson** [dsuryd/dotNetify-react-template#47]
First of all this is great library and I'm going to circle back on it almost a year after I discovered it and see if its implementation is right for what we are trying to do. For a customer facing web site SEO is very important so with out ssr its a no go. I read up on some comments but cant find an implementation that works for dotnetify. Preferable in the Micro-Fronted model.  

https://hackernoon.com/server-side-rendering-of-deep-links-with-react-and-net-core-882830ca663
All of the ssr documentation leads to a not working solution.

**Comment by dsuryd** [comment]
SSR issue has been fixed in release v3.7.  Working demo is here: [https://github.com/dsuryd/dotNetify/tree/master/Demo/React/LazyLoadRouting](https://github.com/dsuryd/dotNetify/tree/master/Demo/React/LazyLoadRouting)

SSR in the context of micro-frontend is a complex topic, and won't be a goal for this library, at least for now.
